-- Fialho Home Improvement — Supabase schema
--
-- Mirrors Filaho-CRM-/schema.md and the shape FialhoDB used to keep in
-- localStorage (app.js), now the real backing store for web/. IDs stay `text`
-- so the values already generated by uid() in the original app (e.g.
-- "cust_mrkv7uwz_3plj9f") carry over as-is, with no remapping of foreign keys.
--
-- Run this once against your Supabase project (SQL Editor or `supabase db
-- push`), then seed.sql, then see web/README or the setup notes for creating
-- an Auth user and linking it via company_members. Safe to re-run — every
-- statement is idempotent (if not exists / drop policy if exists).

-- ── companies ────────────────────────────────────────────────────────────
create table if not exists companies (
  id text primary key,
  name text not null,
  slug text not null unique,
  logo text,
  color text,
  accent text,
  industry text,
  settings jsonb not null default '{}'::jsonb
);

-- ── pipeline_stages (per-company lead pipeline columns) ─────────────────
create table if not exists pipeline_stages (
  id text not null,
  company_id text not null references companies(id) on delete cascade,
  name text not null,
  "order" int not null default 0,
  color text,
  type text,
  primary key (company_id, id)
);

-- ── company_services (per-company service type list) ────────────────────
create table if not exists company_services (
  company_id text not null references companies(id) on delete cascade,
  service text not null,
  position int not null default 0,
  primary key (company_id, service)
);

-- ── users (app profile row, separate from Supabase auth.users) ──────────
create table if not exists users (
  id text primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null unique,
  role text not null default 'member',
  permissions text[] not null default '{}'::text[]
);

-- ── company_members (links a Supabase Auth user to accessible companies) ─
-- Used by RLS policies below. One row per (auth user, company) they can access.
create table if not exists company_members (
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id text not null references companies(id) on delete cascade,
  role text not null default 'member',
  primary key (user_id, company_id)
);

-- ── customers (the "Clients" module) ─────────────────────────────────────
create table if not exists customers (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  status text not null default 'active',
  service_type text default '',
  source text default 'Manual',
  notes text default '',
  drive_folder_url text default '',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists customers_company_id_idx on customers(company_id);

-- ── leads (pipeline opportunities, linked to a customer) ────────────────
create table if not exists leads (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  stage_id text not null default 'new',
  service_type text default '',
  value numeric not null default 0,
  source text default 'Manual',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists leads_company_id_idx on leads(company_id);
create index if not exists leads_customer_id_idx on leads(customer_id);

-- ── jobs ──────────────────────────────────────────────────────────────
-- customer_name/notes/source/source_uid mirror app.js's cleanJob() shape —
-- source_uid in particular is what findDuplicateJob() matches on to avoid
-- re-creating the same event on a repeat calendar import.
create table if not exists jobs (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  lead_id text references leads(id) on delete set null,
  title text not null,
  customer_name text default '',
  status text not null default 'planned',
  service_type text default '',
  scheduled_date date,
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  estimated_value numeric not null default 0,
  notes text default '',
  source text default 'Manual',
  source_uid text default '',
  drive_folder_url text default '',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- Idempotent for databases where `jobs` already exists from an earlier run
-- of this file, before these columns were added.
alter table jobs add column if not exists customer_name text default '';
alter table jobs add column if not exists notes text default '';
alter table jobs add column if not exists source text default 'Manual';
alter table jobs add column if not exists source_uid text default '';
alter table jobs add column if not exists google_event_id text;
create index if not exists jobs_company_id_idx on jobs(company_id);

-- ── imports (CSV/ICS/Sheets import history) ──────────────────────────────
create table if not exists imports (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  file_name text,
  source_type text,
  imported_at timestamptz not null default now(),
  created_count int not null default 0,
  updated_count int not null default 0,
  skipped_count int not null default 0,
  row_count int not null default 0
);
create index if not exists imports_company_id_idx on imports(company_id);

-- ── notes (free-form notes attached to any entity) ───────────────────────
create table if not exists notes (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  body text not null,
  created_at timestamptz not null default now(),
  user_id text references users(id) on delete set null
);
create index if not exists notes_company_id_idx on notes(company_id);
create index if not exists notes_entity_idx on notes(entity_type, entity_id);

-- ── files (links to Drive/other providers, attached to an entity) ───────
create table if not exists files (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  name text not null,
  url text not null,
  provider text default 'google_drive',
  created_at timestamptz not null default now()
);
create index if not exists files_company_id_idx on files(company_id);

-- ── supplier_products / supplier_price_history (scraped dealer catalogs) ─
-- Populated by scripts/scrape-muses.mjs (GitHub Actions, weekly), never by
-- the app itself — writes go through the service_role key, which bypasses
-- RLS, so these two tables intentionally get a select-only policy below
-- instead of joining the customers/leads/... CRUD loop further down.
create table if not exists supplier_products (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references companies(id),
  supplier text not null,
  external_id text not null,
  sku text not null,
  item_class text,
  item_category text,
  cabinet_type text,
  color text,
  detail text,
  description text,
  width_in numeric,
  height_in numeric,
  depth_in numeric,
  weight numeric,
  price numeric,
  stock integer,
  is_available boolean,
  is_fixed_price boolean,
  raw jsonb,
  scraped_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, supplier, external_id)
);
create index if not exists supplier_products_company_supplier_idx on supplier_products(company_id, supplier);

create table if not exists supplier_price_history (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references companies(id),
  supplier text not null,
  external_id text not null,
  sku text not null,
  price numeric,
  stock integer,
  recorded_at timestamptz not null default now()
);
create index if not exists supplier_price_history_lookup_idx on supplier_price_history(company_id, supplier, external_id, recorded_at desc);

-- ── meta_ads_insights (daily ad performance, one row per company/campaign/day) ─
-- Populated by scripts/sync-meta-ads.mjs (GitHub Actions, daily), never by
-- the app itself — same service_role-writes/select-only-RLS shape as
-- supplier_products above. Read by Reports.tsx via data/metaAds.ts.
create table if not exists meta_ads_insights (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references companies(id),
  date date not null,
  campaign_id text not null,
  campaign_name text,
  spend numeric,
  impressions integer,
  clicks integer,
  ctr numeric,
  cpc numeric,
  synced_at timestamptz not null default now(),
  unique (company_id, campaign_id, date)
);
create index if not exists meta_ads_insights_company_date_idx on meta_ads_insights(company_id, date desc);

-- ── google_oauth_tokens (per-company refresh token for background sync) ──
-- Populated by web/api/google-oauth-callback.js after the OAuth redirect
-- flow, consumed by scripts/sync-google-calendar.mjs (GitHub Actions cron).
-- Deliberately gets ZERO RLS policies below (not even select) — a refresh
-- token can mint fresh Google access on its own, so it must never be
-- reachable through the app's anon/authenticated client, only service_role.
create table if not exists google_oauth_tokens (
  company_id text primary key references companies(id) on delete cascade,
  refresh_token text not null,
  scope text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── integration_settings (single shared blob, not per company) ──────────
-- Mirrors the single `db.integration_settings` object app.js keeps in
-- localStorage today — one Google Maps API key / OAuth client / etc. shared
-- across every company the signed-in user can see. Per-company values
-- (Drive folder URLs, Calendar IDs, Sheets source URLs) are nested dicts
-- keyed by company_id *inside* this blob, same nesting as the original app.
create table if not exists integration_settings (
  id text primary key default 'default',
  settings jsonb not null default '{}'::jsonb
);

-- ═══════════════════════════════════════════════════════════════════════
-- RLS (Phase 2 — enabled now that Supabase Auth + company_members are wired)
-- ═══════════════════════════════════════════════════════════════════════
-- Every operational table only exposes rows whose company_id is one the
-- signed-in auth user has a company_members row for. Delete policy added
-- alongside the Delete action in RecordModal (customers/leads/jobs).

do $$
declare t text;
begin
  foreach t in array array[
    'customers','leads','jobs','imports','notes','files',
    'pipeline_stages','company_services'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_select', t);
    execute format(
      'create policy %I on %I for select using (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_select', t);
    execute format('drop policy if exists %I on %I', t || '_insert', t);
    execute format(
      'create policy %I on %I for insert with check (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_insert', t);
    execute format('drop policy if exists %I on %I', t || '_update', t);
    execute format(
      'create policy %I on %I for update using (
         company_id in (select company_id from company_members where user_id = auth.uid())
       ) with check (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_update', t);
    execute format('drop policy if exists %I on %I', t || '_delete', t);
    execute format(
      'create policy %I on %I for delete using (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_delete', t);
  end loop;
end $$;

-- Pin company_id as immutable after creation (found during a 2026-08-26
-- follow-up security audit). The UPDATE policy above checks company
-- membership independently on the row's old and new company_id -- never that
-- they're the SAME company -- so a user who legitimately belongs to two
-- companies (a normal, supported account state: see CompanyPicker.tsx) could
-- move a record from one tenant's dataset into the other's via a direct
-- PostgREST PATCH, e.g. `{"company_id": "<other company>"}`, bypassing the
-- app UI (which never does this) entirely. RLS alone can't express "old and
-- new must match" in a `with check` clause, so this needs a trigger.
create or replace function pin_company_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.company_id is distinct from old.company_id then
    raise exception 'company_id cannot be changed after creation';
  end if;
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'customers','leads','jobs','imports','notes','files',
    'pipeline_stages','company_services'
  ] loop
    execute format('drop trigger if exists %I on %I', t || '_pin_company', t);
    execute format(
      'create trigger %I before update on %I for each row execute function pin_company_id()',
      t || '_pin_company', t);
  end loop;
end $$;

-- Read-only for app users; written only by scripts/scrape-muses.mjs via the
-- service_role key (bypasses RLS), so no insert/update/delete policy here.
alter table supplier_products enable row level security;
drop policy if exists supplier_products_select on supplier_products;
create policy supplier_products_select on supplier_products for select using (
  company_id in (select company_id from company_members where user_id = auth.uid())
);

alter table supplier_price_history enable row level security;
drop policy if exists supplier_price_history_select on supplier_price_history;
create policy supplier_price_history_select on supplier_price_history for select using (
  company_id in (select company_id from company_members where user_id = auth.uid())
);

alter table meta_ads_insights enable row level security;
drop policy if exists meta_ads_insights_select on meta_ads_insights;
create policy meta_ads_insights_select on meta_ads_insights for select using (
  company_id in (select company_id from company_members where user_id = auth.uid())
);

-- No policies created — enabling RLS with zero grants blocks the anon/
-- authenticated client entirely; only service_role (which bypasses RLS) can
-- read or write this table.
alter table google_oauth_tokens enable row level security;

alter table companies enable row level security;
drop policy if exists companies_select on companies;
create policy companies_select on companies for select using (
  id in (select company_id from company_members where user_id = auth.uid())
);

alter table company_members enable row level security;
drop policy if exists company_members_select on company_members;
create policy company_members_select on company_members for select using (
  user_id = auth.uid()
);

-- `users` was the one table in this schema that never got RLS enabled (found
-- during a 2026-08-26 security audit — every other table has a policy below
-- or above this line, this one never did). Without it, any authenticated
-- user could select every row via a direct PostgREST call regardless of the
-- app's own narrow `select("id, name")` usage, exposing every user's email/
-- role/permissions across every company. Scope: a user can see their own
-- row, or any user who shares at least one company with them (covers the
-- app's actual need — mapping a note's/file's user_id to a name within a
-- company both users belong to). No insert/update/delete policy: user
-- provisioning stays service_role-only, same as company_members.
alter table users enable row level security;
drop policy if exists users_select on users;
create policy users_select on users for select using (
  auth_user_id = auth.uid()
  or exists (
    select 1
    from company_members cm_self
    join company_members cm_other on cm_other.company_id = cm_self.company_id
    where cm_self.user_id = auth.uid()
      and cm_other.user_id = users.auth_user_id
  )
);

-- integration_settings isn't company-scoped (see table comment above), so its
-- policy just checks the user belongs to at least one company rather than
-- checking a specific company_id.
alter table integration_settings enable row level security;
-- Direct SELECT on the base table is intentionally NOT granted (found during
-- a 2026-08-26 follow-up security audit): a prior fix added
-- get_my_integration_settings() below to filter per-company nested keys down
-- to only the caller's own companies, but RLS operates at row granularity,
-- not JSONB-key granularity -- an "any company member" SELECT policy on the
-- row would still let any authenticated user bypass the filtering RPC by
-- calling GET /rest/v1/integration_settings directly and reading every
-- tenant's nested config. The RPC itself is SECURITY DEFINER, so revoking
-- the base table's grant does not affect it -- it runs as the function
-- owner, not the caller's `authenticated` role.
drop policy if exists integration_settings_select on integration_settings;
revoke select on integration_settings from authenticated;
-- The app's saveIntegrationSettings() does a plain .upsert({id:"default",...}),
-- which Postgres executes as INSERT ... ON CONFLICT (id) DO UPDATE and needs
-- SELECT on the conflict-target column to detect the existing row -- grant
-- that one column back (not `settings`) so writes keep working.
grant select (id) on integration_settings to authenticated;
drop policy if exists integration_settings_insert on integration_settings;
create policy integration_settings_insert on integration_settings for insert with check (
  exists (select 1 from company_members where user_id = auth.uid())
);
drop policy if exists integration_settings_update on integration_settings;
create policy integration_settings_update on integration_settings for update using (
  exists (select 1 from company_members where user_id = auth.uid())
) with check (
  exists (select 1 from company_members where user_id = auth.uid())
);

-- Two guards added 2026-08-26 (security audit) on top of the intentionally
-- broad "any company member" policy above. The policy still lets any member
-- of ANY company pass the RLS check for this shared row (that part is
-- unchanged, by design) -- these close the two things that were actually
-- wrong: a member of company A could previously READ every other company's
-- nested Drive/Calendar/Meta Ads config (not just their own), and could
-- WRITE over another company's nested keys with a crafted full-object
-- upsert. Neither the app's TypeScript types nor any existing call site
-- needs to change: reads go through get_my_integration_settings() (same
-- shape back), and writes still succeed exactly as before as long as they
-- only touch the caller's own company's keys -- which is all the app's UI
-- ever legitimately does.

-- Read guard: returns the shared row with every per-company nested dict
-- filtered down to only the keys (company ids) the caller actually belongs
-- to. Shared, non-tenant-specific fields (google_oauth, google_maps,
-- google_drive.picker_api_key, email_sms, meta_ads.enabled/notes) pass
-- through unfiltered, matching this table's documented "shared blob" intent.
create or replace function get_my_integration_settings()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  raw jsonb;
  my_companies text[];
  filtered jsonb;
  scoped_paths text[][] := array[
    array['google_calendar', 'calendar_ids'],
    array['google_sheets', 'spreadsheet_ids'],
    array['google_sheets', 'source_urls'],
    array['google_drive', 'folder_ids'],
    array['google_drive', 'folder_urls'],
    array['meta_ads', 'ad_account_ids']
  ];
  path text[];
  raw_dict jsonb;
  filtered_dict jsonb;
  k text;
begin
  select settings into raw from integration_settings where id = 'default';
  if raw is null then return '{}'::jsonb; end if;

  select coalesce(array_agg(company_id), array[]::text[]) into my_companies
  from company_members where user_id = auth.uid();

  filtered := raw;
  foreach path slice 1 in array scoped_paths loop
    raw_dict := coalesce(raw #> path, '{}'::jsonb);
    filtered_dict := '{}'::jsonb;
    for k in select jsonb_object_keys(raw_dict) loop
      if k = any(my_companies) then
        filtered_dict := filtered_dict || jsonb_build_object(k, raw_dict -> k);
      end if;
    end loop;
    filtered := jsonb_set(filtered, path, filtered_dict);
  end loop;

  return filtered;
end;
$$;
grant execute on function get_my_integration_settings() to authenticated;

-- Write guard: a BEFORE UPDATE trigger (not a `with check`, since expressing
-- "only these specific nested keys may differ" per-key isn't possible in a
-- plain RLS check clause) that rejects any update touching a per-company
-- nested key the caller doesn't belong to, whether from a malicious crafted
-- payload or a concurrent-edit lost-update race between two companies.
create or replace function enforce_integration_settings_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  my_companies text[];
  scoped_paths text[][] := array[
    array['google_calendar', 'calendar_ids'],
    array['google_sheets', 'spreadsheet_ids'],
    array['google_sheets', 'source_urls'],
    array['google_drive', 'folder_ids'],
    array['google_drive', 'folder_urls'],
    array['meta_ads', 'ad_account_ids']
  ];
  path text[];
  old_dict jsonb;
  new_dict jsonb;
  merged_dict jsonb;
  k text;
begin
  -- service_role connections (background scripts, if any are ever added for
  -- this table) carry no end-user JWT, so auth.uid() is null here — RLS
  -- already lets service_role bypass everything, so this trigger should too
  -- rather than treating "no companies" as "no changes are ever allowed."
  if auth.uid() is null then
    return new;
  end if;

  select coalesce(array_agg(company_id), array[]::text[]) into my_companies
  from company_members where user_id = auth.uid();

  -- Fixed 2026-08-26 (follow-up audit): the caller's `new.settings` was
  -- always built from get_my_integration_settings()'s read, which already
  -- filters every OTHER company's keys out before the client ever sees them
  -- -- so those keys are structurally *absent* from new_dict, not merely
  -- unchanged. The original version of this loop treated "absent from
  -- new_dict" the same as "explicitly deleted," which raised a false
  -- "not authorized" exception on every save by any company other than
  -- whichever one happened to populate a shared key first. This version
  -- only raises when the caller's payload explicitly supplies a *different*
  -- value for a key outside their own companies (genuine tampering), and
  -- otherwise carries the old value forward into what actually gets written,
  -- so a company's data is never silently dropped by someone else's save.
  foreach path slice 1 in array scoped_paths loop
    old_dict := coalesce(old.settings #> path, '{}'::jsonb);
    new_dict := coalesce(new.settings #> path, '{}'::jsonb);
    merged_dict := new_dict;
    for k in select jsonb_object_keys(old_dict) loop
      if not (k = any(my_companies)) then
        if (new_dict ? k) and (old_dict -> k) is distinct from (new_dict -> k) then
          raise exception 'not authorized to modify integration settings for company %', k;
        end if;
        merged_dict := jsonb_set(merged_dict, array[k], old_dict -> k);
      end if;
    end loop;
    new.settings := jsonb_set(new.settings, path, merged_dict);
  end loop;
  return new;
end;
$$;

drop trigger if exists integration_settings_scope_guard on integration_settings;
create trigger integration_settings_scope_guard
  before update on integration_settings
  for each row execute function enforce_integration_settings_scope();
