-- Fialho CRM — Supabase schema
--
-- Mirrors Filaho-CRM-/schema.md and the shape FialhoDB used to keep in
-- localStorage (app.js), now the real backing store for web/. IDs stay `text`
-- so the values already generated by uid() in the original app (e.g.
-- "cust_mrkv7uwz_3plj9f") carry over as-is, with no remapping of foreign keys.
--
-- Run this once against your Supabase project (SQL Editor or `supabase db
-- push`), then seed.sql, then see web/README or the setup notes for creating
-- an Auth user and linking it via company_members. Safe to re-run — every
-- statement is idempotent (if not exists / drop policy if exists).

-- ── companies ────────────────────────────────────────────────────────────
create table if not exists companies (
  id text primary key,
  name text not null,
  slug text not null unique,
  logo text,
  color text,
  accent text,
  industry text,
  settings jsonb not null default '{}'::jsonb
);

-- ── pipeline_stages (per-company lead pipeline columns) ─────────────────
create table if not exists pipeline_stages (
  id text not null,
  company_id text not null references companies(id) on delete cascade,
  name text not null,
  "order" int not null default 0,
  color text,
  type text,
  primary key (company_id, id)
);

-- ── company_services (per-company service type list) ────────────────────
create table if not exists company_services (
  company_id text not null references companies(id) on delete cascade,
  service text not null,
  position int not null default 0,
  primary key (company_id, service)
);

-- ── users (app profile row, separate from Supabase auth.users) ──────────
create table if not exists users (
  id text primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null unique,
  role text not null default 'member',
  permissions text[] not null default '{}'::text[]
);

-- ── company_members (links a Supabase Auth user to accessible companies) ─
-- Used by RLS policies below. One row per (auth user, company) they can access.
create table if not exists company_members (
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id text not null references companies(id) on delete cascade,
  role text not null default 'member',
  primary key (user_id, company_id)
);

-- ── customers (the "Clients" module) ─────────────────────────────────────
create table if not exists customers (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  status text not null default 'active',
  service_type text default '',
  source text default 'Manual',
  notes text default '',
  drive_folder_url text default '',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists customers_company_id_idx on customers(company_id);

-- ── leads (pipeline opportunities, linked to a customer) ────────────────
create table if not exists leads (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  stage_id text not null default 'new',
  service_type text default '',
  value numeric not null default 0,
  source text default 'Manual',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists leads_company_id_idx on leads(company_id);
create index if not exists leads_customer_id_idx on leads(customer_id);

-- ── jobs ──────────────────────────────────────────────────────────────
-- customer_name/notes/source/source_uid mirror app.js's cleanJob() shape —
-- source_uid in particular is what findDuplicateJob() matches on to avoid
-- re-creating the same event on a repeat calendar import.
create table if not exists jobs (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  lead_id text references leads(id) on delete set null,
  title text not null,
  customer_name text default '',
  status text not null default 'planned',
  service_type text default '',
  scheduled_date date,
  address text default '',
  city text default '',
  state text default '',
  zip text default '',
  estimated_value numeric not null default 0,
  notes text default '',
  source text default 'Manual',
  source_uid text default '',
  drive_folder_url text default '',
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- Idempotent for databases where `jobs` already exists from an earlier run
-- of this file, before these columns were added.
alter table jobs add column if not exists customer_name text default '';
alter table jobs add column if not exists notes text default '';
alter table jobs add column if not exists source text default 'Manual';
alter table jobs add column if not exists source_uid text default '';
create index if not exists jobs_company_id_idx on jobs(company_id);

-- ── imports (CSV/ICS/Sheets import history) ──────────────────────────────
create table if not exists imports (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  file_name text,
  source_type text,
  imported_at timestamptz not null default now(),
  created_count int not null default 0,
  updated_count int not null default 0,
  skipped_count int not null default 0,
  row_count int not null default 0
);
create index if not exists imports_company_id_idx on imports(company_id);

-- ── notes (free-form notes attached to any entity) ───────────────────────
create table if not exists notes (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  body text not null,
  created_at timestamptz not null default now(),
  user_id text references users(id) on delete set null
);
create index if not exists notes_company_id_idx on notes(company_id);
create index if not exists notes_entity_idx on notes(entity_type, entity_id);

-- ── files (links to Drive/other providers, attached to an entity) ───────
create table if not exists files (
  id text primary key,
  company_id text not null references companies(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  name text not null,
  url text not null,
  provider text default 'google_drive',
  created_at timestamptz not null default now()
);
create index if not exists files_company_id_idx on files(company_id);

-- ── integration_settings (single shared blob, not per company) ──────────
-- Mirrors the single `db.integration_settings` object app.js keeps in
-- localStorage today — one Google Maps API key / OAuth client / etc. shared
-- across every company the signed-in user can see. Per-company values
-- (Drive folder URLs, Calendar IDs, Sheets source URLs) are nested dicts
-- keyed by company_id *inside* this blob, same nesting as the original app.
create table if not exists integration_settings (
  id text primary key default 'default',
  settings jsonb not null default '{}'::jsonb
);

-- ═══════════════════════════════════════════════════════════════════════
-- RLS (Phase 2 — enabled now that Supabase Auth + company_members are wired)
-- ═══════════════════════════════════════════════════════════════════════
-- Every operational table only exposes rows whose company_id is one the
-- signed-in auth user has a company_members row for. No delete policy —
-- the app has no delete functionality today.

do $$
declare t text;
begin
  foreach t in array array[
    'customers','leads','jobs','imports','notes','files',
    'pipeline_stages','company_services'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_select', t);
    execute format(
      'create policy %I on %I for select using (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_select', t);
    execute format('drop policy if exists %I on %I', t || '_insert', t);
    execute format(
      'create policy %I on %I for insert with check (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_insert', t);
    execute format('drop policy if exists %I on %I', t || '_update', t);
    execute format(
      'create policy %I on %I for update using (
         company_id in (select company_id from company_members where user_id = auth.uid())
       ) with check (
         company_id in (select company_id from company_members where user_id = auth.uid())
       )', t || '_update', t);
  end loop;
end $$;

alter table companies enable row level security;
drop policy if exists companies_select on companies;
create policy companies_select on companies for select using (
  id in (select company_id from company_members where user_id = auth.uid())
);

alter table company_members enable row level security;
drop policy if exists company_members_select on company_members;
create policy company_members_select on company_members for select using (
  user_id = auth.uid()
);

-- integration_settings isn't company-scoped (see table comment above), so its
-- policy just checks the user belongs to at least one company rather than
-- checking a specific company_id.
alter table integration_settings enable row level security;
drop policy if exists integration_settings_select on integration_settings;
create policy integration_settings_select on integration_settings for select using (
  exists (select 1 from company_members where user_id = auth.uid())
);
drop policy if exists integration_settings_insert on integration_settings;
create policy integration_settings_insert on integration_settings for insert with check (
  exists (select 1 from company_members where user_id = auth.uid())
);
drop policy if exists integration_settings_update on integration_settings;
create policy integration_settings_update on integration_settings for update using (
  exists (select 1 from company_members where user_id = auth.uid())
) with check (
  exists (select 1 from company_members where user_id = auth.uid())
);
